package com.wutsi.flutter.sdui.enums

enum class WidgetType {
    AppBar,
    Button,
    CircleAvatar,
    Column,
    Container,
    Dialog,
    Divider,
    DropdownButton,
    DropdownMenuItem,
    Flexible,
    Form,
    Icon,
    IconButton,
    Image,
    Input,
    ListView,
    ListItem,
    ListItemSwitch,
    MoneyText,
    MoneyWithKeyboard,
    MoneyWithSlider,
    Page,
    PageView,
    PinWithKeyboard,
    Row,
    Radio,
    RadioGroup,
    Spacer,
    Text,
    Screen,
}
